version: '3.7'

x-env-defaults: &env
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  TERMINUS_TIMEOUT: 1000
  TERMINUS_SHUTDOWN_DELAY: 0
  YARN_CACHE_FOLDER: /.yarn-cache

x-node-defaults: &node
  tty: true
  init: true
  image: node:14.15-alpine
  working_dir: /smoketrax
  restart: always
  volumes:
    - .:/smoketrax:cached
    - ./node_modules:/smoketrax/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  mongodb:
    tty: true
    image: mongo:4.0
    volumes:
      - mongodb:/data/db
    ports:
      - "44909:27017"
  api:
    <<: *node
    working_dir: /smoketrax/api
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *env
      MONGO_URI: ${MONGO_URI-mongodb://mongodb:27017}
    depends_on:
      - mongodb
    ports:
      - "44910:44910"

volumes:
  yarn-cache: {}
  mongodb: {}
