version: '3.7'

x-env-defaults: &env
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  TERMINUS_TIMEOUT: 1000
  TERMINUS_SHUTDOWN_DELAY: 0
  YARN_CACHE_FOLDER: /.yarn-cache

x-node-defaults: &node
  tty: true
  init: true
  image: node:14.15-alpine
  working_dir: /smoketrax
  restart: always
  volumes:
    - .:/smoketrax:cached
    - ./node_modules:/smoketrax/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  api:
    <<: *node
    working_dir: /smoketrax/api
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *env
      APP_URL: ${APP_URL-http://0.0.0.0:44911}
      MONGO_URI: ${MONGO_URI-mongodb://root:password123@mongodb-primary:27017,mongodb-secondary:27017/smoketrax?replicaSet=smoketrax&authSource=admin&readPreference=primary}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      TOKEN_SECRET: ${TOKEN_SECRET-thisisntsecretandyoushouldusesomethingdifferentinproductiondawg}
    depends_on:
      - mongodb-secondary
    ports:
      - "44910:44910"

  mongodb-primary:
    image: bitnami/mongodb:4.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=smoketrax
    volumes:
      - mongodb_primary:/bitnami
    ports:
      - "44901:27017"

  mongodb-secondary:
    image: bitnami/mongodb:4.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=smoketrax
    volumes:
      - mongodb_secondary:/bitnami


volumes:
  yarn-cache: {}
  mongodb_primary: {}
  mongodb_secondary: {}
